export {default as Tree} from './components/Tree.vue'
export {default as Fold} from './plugins/fold.js'
export {default as Check} from './plugins/check.js'
export {default as NodeBack} from './plugins/NodeBack.vue'
export {default as Draggable} from './plugins/draggable/Draggable.vue'
