export {default as Tree} from './components/Tree.vue'
export {default as PluginCheck} from './plugins/check.js'
export {default as PluginFold} from './plugins/fold.js'
export {default as PluginNodeBack} from './plugins/NodeBack.vue'
export {default as PluginDraggable} from './plugins//draggable/Draggable.vue'
